/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 head.glb
*/
import React, { useRef } from 'react'

import { useGLTF } from '@react-three/drei'
import { Group, MeshPhysicalMaterial } from 'three'

import { useHead } from './useHead'

export function Head(props: any) {
  const { nodes, materials } = useGLTF('/head.glb') as any
  const pinMaterial = new MeshPhysicalMaterial({
    roughness: -0.1,
    transmission: 1,
    transparent: true,
    opacity: 0.5,
    color: '#333'
  })
  const headRef = useRef<Group>(null!)
  useHead({ headRef })

  return (
    <group
      {...props}
      dispose={null}
      scale={2.8}
      rotation={[0.4, Math.PI, 0]}
      ref={headRef}
    >
      <group
        position={[0, 0.19, -0.24]}
        rotation={[Math.PI / 2, 0, 3.13]}
        scale={0.12}
      >
        <group position={[0, 0.03, 0.44]}>
          <group
            position={[-7.01, 1.7, -0.51]}
            rotation={[-0.19, 0, -0.22]}
            scale={1.35}
          >
            <mesh
              geometry={nodes.Mesh001.geometry}
              material={materials.blinn3}
            />
            <mesh
              geometry={nodes.Mesh001_1.geometry}
              material={materials.blinn1}
            />
            <mesh
              geometry={nodes.Mesh001_2.geometry}
              material={materials.blinn2}
            />
          </group>
          <mesh
            geometry={nodes.p2.geometry}
            material={materials.blinn2}
            position={[-5.71, 8.32, -2.68]}
            rotation={[-0.19, 0, -0.22]}
            scale={[0.31, 0.31, 0.34]}
          />
        </group>
        <mesh geometry={nodes.glass.geometry}>
          <meshPhysicalMaterial
            color={'#ffffff'}
            transparent={true}
            opacity={0.4}
          />
        </mesh>
        <mesh geometry={nodes.structure.geometry} material={pinMaterial} />
        <group position={[7.69, -2.64, 1.17]} rotation={[-0.2, 0.02, 0.21]}>
          <mesh geometry={nodes.Mesh006.geometry} material={materials.blinn3} />
          <mesh
            geometry={nodes.Mesh006_1.geometry}
            material={materials.blinn1}
          />
          <mesh
            geometry={nodes.Mesh006_2.geometry}
            material={materials.blinn2}
          />
        </group>
        <mesh
          geometry={nodes.pin3.geometry}
          material={materials.blinn2}
          position={[6.42, 3.98, -1.03]}
          rotation={[-0.2, 0.02, 0.21]}
        />
        <mesh
          geometry={nodes.pin4.geometry}
          material={materials.blinn2}
          position={[6.68, 3.33, -1.01]}
          rotation={[-0.2, 0.02, 0.21]}
        />
      </group>
      <mesh
        geometry={nodes.Face.geometry}
        material={materials['Material.002']}
      />
      <mesh
        geometry={nodes.Hair.geometry}
        material={materials['Material.001']}
        position={[1, -1.01, 0]}
      />
      <mesh
        geometry={nodes.LEye.geometry}
        material={materials['Material.003']}
        position={[0.32, 0.14, -0.78]}
        scale={[0.09, 0.08, 0.08]}
      />
      <mesh
        geometry={nodes.REye.geometry}
        material={materials['Material.003']}
        position={[-0.32, 0.15, -0.77]}
        scale={[0.09, 0.08, 0.08]}
      />
      <mesh
        geometry={nodes.Nose.geometry}
        material={materials['Material.003']}
        position={[0.01, -0.03, -0.88]}
        rotation={[0.41, 0, 0]}
        scale={[0.01, 0.06, 0.07]}
      />
      <mesh
        geometry={nodes.Mouth.geometry}
        material={materials['Material.003']}
        position={[-0.04, -0.2, -1.23]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.004']}
        position={[0.48, -0.03, -0.87]}
        rotation={[-1.11, -0.1, -0.28]}
        scale={[0.12, 0.01, 0.05]}
      />
      <mesh
        geometry={nodes.BezierCurve001.geometry}
        material={materials['Material.003']}
        position={[0.5, -0.02, -0.87]}
      />
      <mesh
        geometry={nodes.BezierCurve002.geometry}
        material={materials['Material.003']}
        position={[-0.47, -0.02, -0.88]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.004']}
        position={[-0.47, -0.03, -0.87]}
        rotation={[-1.14, 0.2, 0.28]}
        scale={[0.12, 0.01, 0.05]}
      />
    </group>
  )
}

useGLTF.preload('/head.glb')
