/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model.gltf --transform
*/
import React from 'react'

import { useGLTF } from '@react-three/drei'

export function Tree(props: any) {
  const { nodes, materials } = useGLTF('/tree-transformed.glb') as any
  return (
    <group {...props} dispose={null} position={[0, -10, 0]}>
      <mesh
        geometry={nodes['tree-lime'].geometry}
        material={materials.color_main}
        castShadow
      />
    </group>
  )
}

useGLTF.preload('/tree-transformed.glb')
