/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/keyboard.glb
*/
import React from 'react'

import { useGLTF } from '@react-three/drei'

import { SpringKeyCap } from './SpringKeyCap'

export function KeyboardModel(props) {
  const { nodes, materials } = useGLTF('/keyboard.glb')
  return (
    <group scale={100} {...props} dispose={null} rotation={[Math.PI / 4, 0, 0]}>
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials.CaseBake}
        position={[0.01, 0, 0.01]}
        rotation={[0.03, 0, 0]}
        scale={[1.34, 1.26, 1.34]}
      />
      <group position={[0.0005, 0, 0]}>
        <SpringKeyCap>
          <mesh geometry={nodes.KeycapTL.geometry} material={materials.SBake} />
        </SpringKeyCap>
        <SpringKeyCap>
          <mesh geometry={nodes.KeycapTR.geometry} material={materials.CBake} />
        </SpringKeyCap>
        <SpringKeyCap>
          <mesh
            geometry={nodes.KeycapBL.geometry}
            material={materials.LBake}
            position={[0, 0, 0.0194]}
          />
        </SpringKeyCap>
        <SpringKeyCap>
          <mesh
            geometry={nodes.KeycapBR.geometry}
            material={materials.TBake}
            position={[0, 0, 0.0194]}
          />
        </SpringKeyCap>
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.BoardBake}
        position={[0.01, 0, 0.01]}
        scale={1.32}
      />
    </group>
  )
}

useGLTF.preload('/keyboard.glb')
